FROM bitnami/kafka:latest

USER root
RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -o /opt/bitnami/yq \
    && chmod +x /opt/bitnami/yq \
    && curl -L https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64 -o /opt/bitnami/jq \
    && chmod +x /opt/bitnami/jq
USER 1001

ENV PATH="/opt/bitnami:$PATH"