services:

  postgres:
    container_name: wcrs-db
    image: postgres
    environment:
      POSTGRES_USER: wcrs
      POSTGRES_PASSWORD: wcrs
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - wcrs-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - wcrs-net
    restart: unless-stopped

  configserver:
    container_name: config-server
    image: mantrasandbox/config-server
    ports:
      - 8888:8080
    networks:
      - wcrs-net
    restart: unless-stopped

  discovery:
    container_name: discovery
    image: mantrasandbox/discovery
    ports:
      - 8761:8761
    networks:
      - wcrs-net
    restart: unless-stopped

  employee:
    container_name: employee
    image: mantrasandbox/employee
    ports:
      - 4000:4000
    networks:
      - wcrs-net
    restart: unless-stopped

networks:
  wcrs-net:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
