### create Employee Request
POST http://localhost:4040/api/v1/employees/create
Content-Type: application/json

{
  "firstName": "Crude",
  "lastName": "Victor",
  "userName": "vikings",
  "NIN": "CM12SD4567YU81",
  "dateOfBirth": "1997-01-01"
}

###