spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: employee

  boot:
    admin:
      client:
        url: http://admin:9090
        enabled: true
        auto-registration: true
        instance:
          name: ${spring.application.name:JSS}

