name: CI - Build Backend Services

on:
    push:
        branches:
            - dev
            - main
        paths:
            - wcrs/services/**
            
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:14.5
                env:
                    POSTGRES_PASSWORD: postgres
                options:
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            #name: Cloning our repo into the runner
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'
