name: CI - Build Backend Services

on:
    push:
        branches:
            - dev
            #- main
        #paths:
            #- services/**

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:14.5
                env:
                    POSTGRES_USER: wcrs
                    POSTGRES_PASSWORD: wcrs
                    POSTGRES_DB: employee
                ports:
                    - 5433:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'

            - name: Build with Maven
              run: mvn -B package --file services/employee/pom.xml
