name: CI - Build Changed Backend Services

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      #- main
    paths:
      - services/backend/** # Trigger only when backend files change

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  DOCKER_HUB_REPO_PREFIX: mantrasandbox/  # Change this

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to get proper git diff

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            services/backend/**

      - name: Identify changed services
        id: changed-services
        run: |
          # Get unique service directories that were changed
          changed_dirs=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Extract service directory (assuming structure services/backend/service-name)
            service_dir=$(dirname "$file" | cut -d'/' -f1-3)
            if [[ ! " ${changed_dirs[@]} " =~ " ${service_dir} " ]]; then
              changed_dirs+=("$service_dir")
            fi
          done
          
          # Convert array to JSON array
          json_array=$(printf '%s\n' "${changed_dirs[@]}" | jq -R . | jq -s .)
          echo "Changed service directories: $json_array"
          
          # Set output
          echo "changed_services=$json_array" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            */target/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build changed Maven projects
        run: |
          echo "Changed services to build: ${{ steps.changed-services.outputs.changed_services }}"
          echo "${{ steps.changed-services.outputs.changed_services }}" | jq -r '.[]' | while read service_dir; do
            if [ -f "$service_dir/pom.xml" ]; then
              echo "Building project in $service_dir..."
              mvn -B package --file "$service_dir/pom.xml" -Dmaven.test.skip=true -Dmaven.repo.local=$HOME/.m2/repository
            else
              echo "No pom.xml found in $service_dir"
            fi
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
          buildkitd-config: |
            [worker.oci]
              enabled = true
              max-parallelism = 4
            [worker.containerd]
              enabled = false

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and push changed Docker images
        run: |
          # First prepare Maven cache
          mkdir -p .m2-cache
          cp -r ~/.m2/repository .m2-cache/
          
          echo "${{ steps.changed-services.outputs.changed_services }}" | jq -r '.[]' | while read service_dir; do
            if [ -f "$service_dir/pom.xml" ]; then
              service_name=$(basename "$service_dir")
              jar_file=$(find "$service_dir/target" -name "*.jar" ! -name "*original*" | head -n 1)
          
              if [ -f "$jar_file" ]; then
                echo "Building Docker image for $service_name..."
                docker buildx build \
                  --push \
                  --tag "${{ env.DOCKER_HUB_REPO_PREFIX }}$service_name:latest" \
                  --cache-to type=local,dest=/tmp/.buildx-cache \
                  --cache-from type=local,src=/tmp/.buildx-cache \
                  --build-arg JAR_FILE=$(basename "$jar_file") \
                  --build-context maven-cache=./.m2-cache \
                  -f "$service_dir/Dockerfile" \
                  "$service_dir"
              else
                echo "No jar file found for $service_name in $service_dir/target/"
              fi
            fi
          done